# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_subscription_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
